### ISSUE TITLE
First day of the week

### ISSUE THREAD

**Issue by mican** [conzett/jquery.dateRange#1]
Hello, I'm looking for simple solution to make Monday first day of the week.

**Comment by conzett** [comment]
Hi mican

I have added a new option: "startDay" which you can initialize the plugin with. It is a zero-based index that corresponds to the day of the week, so use 1 for Monday. I have updated the downloads as well.

Thanks so much for reporting it! I apologize for my Americentrism regarding the calendar structure :)
